site_name: CTF101-Labs-2023
site_url: https://courses.zjusec.com/
repo_name: summer_course_2023
repo_url: https://github.com/team-s2/summer_course_2023/
edit_uri: tree/master/docs
copyright: Copyright &copy; 2023 ZJU AAA