site_name: CTF101-Labs-2023
site_url: https://courses.zjusec.com/
repo_name: summer_course_2023
repo_url: https://github.com/team-s2/summer_course_2023/
edit_uri: tree/master/docs
copyright: Copyright &copy; 2023 ZJU AAA

nav:
  - 首页: index.md
  - 工具部分:
    - "相关工具的介绍和使用": intro/tools.md
  - 导论部分:
    - "general lab 0: 基础知识及技能": intro/lab0.md
    - "web lab 1: 常见漏洞": intro/web-lab1.md
    - "misc lab 1: 编解码及 OSINT": intro/misc-lab1.md
    - "rev lab 1: Baby Reverse": intro/rev-lab1.md
    - "pwn lab 1: Code Injection": intro/pwn-lab1.md
    - "crypto lab 1: 逆元、RSA和离散对数": intro/crypto-lab1.md
  - 专题部分:
    - "misc lab 2: 图片、音频隐写": topic/misc-lab2.md
    - "misc lab 3: 流量、内存取证": topic/misc-lab3.md
    - "rev lab 2: CrackMe & Malware": topic/rev-lab2.md
    - "rev lab 3: 迷宫问题": topic/rev-lab3.md
    - "crypto lab 2: AES, RSA & LWE": topic/crypto-lab2.md
    - "crypto lab 3: ECC & Paillier": topic/crypto-lab3.md
    - "web lab 2: PHP/SQL Basics": topic/web-lab2.md
    - "web lab 3: PHP unserialization": topic/web-lab3.md
    - "pwn lab 2: BOF and ROP": topic/pwn-lab2.md
    - "pwn lab 3: More ROP plz": topic/pwn-lab3.md
  - 反馈部分:
    - "misc lab 1 批改反馈": feedback/misc-lab1.md
    - "misc lab 2/3 批改反馈": feedback/misc-lab23.md
